language: node_js

sudo: false

cache: yarn

before_install:
  - cd Resources/Private/Scripts/YoastInfoView

install:
  - yarn install

jobs:
  include:
    - stage: inspector view
      script: yarn build-inspector
    - stage: preview mode
      script: yarn build-app
