-
  name: 'Yoast.YoastSeoForNeos:Data'
  uriPattern: 'neosyoastseo/data/{@action}'
  defaults:
    '@package':    'Yoast.YoastSeoForNeos'
    '@controller': 'Data'
    '@format':     'json'
    '@action':     'query'
  appendExceedingArguments: true

-
  name: 'Yoast.YoastSeoForNeos:Page'
  uriPattern: 'neosyoastseo/page/{@action}'
  defaults:
    '@package':    'Yoast.YoastSeoForNeos'
    '@controller': 'Page'
    '@format':     'html'
    '@action':     'renderPreviewPage'
  appendExceedingArguments: true
